FROM python:3.10

ARG FASTAPI_PORT=8088

ENV FASTAPI_PORT=${FASTAPI_PORT}

WORKDIR /api

COPY ./ /api

RUN pip install --upgrade pip && pip3 install --upgrade -r /api/requirements.txt

CMD python3 /api/main.py