FROM komodoofficial/komodo:cd_release_41265fb_master

LABEL maintainer="smk@komodoplatform.com"

# Setup up user and working directory
ENV GROUP_ID=${GROUP_ID:-1000}
ENV USER_ID=${USER_ID:-1000}
RUN addgroup --gid ${GROUP_ID} notarygroup
RUN adduser --disabled-password --gecos '' --uid ${USER_ID} --gid ${GROUP_ID} komodian
WORKDIR /home/komodian

RUN PATH=/usr/local/bin/:$PATH
RUN apt update && apt install -y nano htop libgomp1

COPY entrypoint.sh /entrypoint.sh
COPY launch_files/ /

# Setup user and working directory
RUN chown -R komodian:notarygroup /home/komodian
USER komodian

ENTRYPOINT ["/entrypoint.sh"]
